### PR TITLE
Add "CLEAR OUT SOUL" instead of "CLEAR USER DATA" and adjust battery voltages in syscon for better battery life.

### PR DESCRIPTION
**Pull request by Switch-modder**
Change the "CLEAR USER DATA" option to "CLEAR OUT SOUL" just like the older versions of wire-os did. Also change the battery voltages in syscon to work better with a newer and larger battery so Vector will hopefully have longer runtime.

### CODE REVIEW

**Comment by Switch-modder** [comment]
I think the battery voltage changes may require recompiling the syscon.

**Comment by Switch-modder** [comment]
(Cries in no response)

**Comment by kercre123** [comment]
please don't touch the syscon voltages

**Comment by Switch-modder** [comment]
Sounds good, I'll change it to just the CCIS.

**Pull request closed without merging**
